spring:
  mail:
    host: smtp.gmail.com # Certifique-se de adicionar o host se for usar o Gmail
    port: 587
    username: #Colocar o email do remetente aqui"
    password: #Colocar a senha gerada no gmail aqui"
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

thymeleaf:
  enable: true

envio:
  email: #"Colocar o email do remetente aqui"
    remetente:
    nomeRemetente: 'Javanauta'

server:
  port: 8082