spring:
  mail:
    host: smtp.gmail.com # Certifique-se de adicionar o host se for usar o Gmail
    port: 587
    username: #digitar email
    password: #digitar seenha email
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

thymeleaf:
  enable: true

envio:
  email:
    remetente: #digitar email
    nomeRemetente: 'Javanauta'

server:
  port: 8082